// coact::coro public handles: Task<T>, Promise<T>, AwaitableRef<T>.
// SPDX-License-Identifier: MIT
//
//   Task<T>         - non-copyable, movable consumer handle. Only observes
//                     completion; never touches the result storage directly.
//   Promise<T>      - non-copyable, non-movable completer handle, taken once
//                     by the task creator. complete()/fail()/cancel() drive
//                     the slot state machine.
//   AwaitableRef<T> - non-copyable, movable read-only observation handle
//                     (is_ready/has_error/take_result/take_error). Waiting is
//                     set_awaiter(): the waiter AO's TargetId + resume signal
//                     are written into the slot; the completion event is
//                     generated by TaskRegistry.
//
// All handles are zero-overhead references: registry pointer + TaskId. They
// become stale after release_task() (next operation returns kInvalidId).
// Single-core model: everything here runs on the single dispatcher thread
// (see task_registry.hpp).
#pragma once

#include <utility>

#include "coact/coro/error.hpp"
#include "coact/coro/task_id.hpp"
#include "coact/config.hpp"
#include "coact/event.hpp"
#include "coact/expected.hpp"

namespace coact {
namespace coro {

template <typename T, typename RegistryT>
class TaskRegistryBaseAccess;
template <typename T, typename PoolT, typename CoordinatorT, uint16_t Capacity>
class TaskRegistry;

// -------------------------------------------------------------------------
// Task<T, RegistryT>: consumer-side handle.
// -------------------------------------------------------------------------
template <typename T, typename RegistryT>
class Task final {
public:
    Task() noexcept : registry_(nullptr), id_(kInvalidTaskId) {}

    Task(RegistryT& registry, TaskId id) noexcept
        : registry_(&registry), id_(id)
    {
    }

    Task(Task&& other) noexcept
        : registry_(other.registry_), id_(other.id_)
    {
        other.registry_ = nullptr;
        other.id_ = kInvalidTaskId;
    }

    Task& operator=(Task&& other) noexcept
    {
        if (this != &other) {
            registry_ = other.registry_;
            id_ = other.id_;
            other.registry_ = nullptr;
            other.id_ = kInvalidTaskId;
        }
        return *this;
    }

    Task(const Task&) = delete;
    Task& operator=(const Task&) = delete;

    bool is_valid() const noexcept
    {
        return (nullptr != registry_) && static_cast<bool>(id_);
    }

    TaskId id() const noexcept { return id_; }

    // Observation (delegates to the registry).
    bool is_ready() const noexcept
    {
        return is_valid() && registry_->is_ready(id_);
    }

    bool has_error() const noexcept
    {
        return is_valid() && registry_->has_error(id_);
    }

    // Register the waiter AO for the completion event. Rejected when the
    // task already has a waiter or is completed.
    Expected<void, TaskError> set_awaiter(TargetId waiter,
                                          uint16_t signal) noexcept
    {
        if (!is_valid()) {
            return Expected<void, TaskError>::error(TaskError::kInvalidId);
        }
        return registry_->set_awaiter(id_, waiter, signal);
    }

    // Release the registry slot. The handle becomes invalid.
    Expected<void, TaskError> release() noexcept
    {
        if (!is_valid()) {
            return Expected<void, TaskError>::error(TaskError::kInvalidId);
        }
        const Expected<void, TaskError> result = registry_->release_task(id_);
        registry_ = nullptr;
        id_ = kInvalidTaskId;
        return result;
    }

    // Internal: registry reference access for AwaitableRef construction.
    RegistryT* registry_of() const noexcept { return registry_; }

private:
    RegistryT* registry_;
    TaskId id_;
};

// -------------------------------------------------------------------------
// Promise<T, RegistryT>: creator-side completer handle (one per task).
// -------------------------------------------------------------------------
template <typename T, typename RegistryT>
class Promise final {
public:
    Promise() noexcept : registry_(nullptr), id_(kInvalidTaskId) {}

    Promise(RegistryT& registry, TaskId id) noexcept
        : registry_(&registry), id_(id)
    {
    }

    Promise(Promise&& other) noexcept
        : registry_(other.registry_), id_(other.id_)
    {
        other.registry_ = nullptr;
        other.id_ = kInvalidTaskId;
    }

    Promise& operator=(Promise&& other) noexcept
    {
        if (this != &other) {
            registry_ = other.registry_;
            id_ = other.id_;
            other.registry_ = nullptr;
            other.id_ = kInvalidTaskId;
        }
        return *this;
    }

    Promise(const Promise&) = delete;
    Promise& operator=(const Promise&) = delete;

    bool is_valid() const noexcept
    {
        return (nullptr != registry_) && static_cast<bool>(id_);
    }

    TaskId id() const noexcept { return id_; }

    // Complete the task with a result value.
    Expected<void, TaskError> complete(const T& value) noexcept
    {
        if (!is_valid()) {
            return Expected<void, TaskError>::error(TaskError::kInvalidId);
        }
        return registry_->complete(id_, value);
    }

    // Complete the task with a failure code.
    Expected<void, TaskError> fail(TaskError err) noexcept
    {
        if (!is_valid()) {
            return Expected<void, TaskError>::error(TaskError::kInvalidId);
        }
        return registry_->fail(id_, err);
    }

    // Cancel a pending task; the waiter (if any) is notified.
    Expected<void, TaskError> cancel() noexcept
    {
        if (!is_valid()) {
            return Expected<void, TaskError>::error(TaskError::kInvalidId);
        }
        return registry_->cancel(id_);
    }

private:
    RegistryT* registry_;
    TaskId id_;
};

// -------------------------------------------------------------------------
// AwaitableRef<T, RegistryT>: read-only observation handle.
// -------------------------------------------------------------------------
template <typename T, typename RegistryT>
class AwaitableRef final {
public:
    AwaitableRef() noexcept : registry_(nullptr), id_(kInvalidTaskId) {}

    AwaitableRef(RegistryT& registry, TaskId id) noexcept
        : registry_(&registry), id_(id)
    {
    }

    AwaitableRef(const Task<T, RegistryT>& task) noexcept
        : registry_(task.registry_of()), id_(task.id())
    {
    }

    AwaitableRef(AwaitableRef&& other) noexcept
        : registry_(other.registry_), id_(other.id_)
    {
        other.registry_ = nullptr;
        other.id_ = kInvalidTaskId;
    }

    AwaitableRef& operator=(AwaitableRef&& other) noexcept
    {
        if (this != &other) {
            registry_ = other.registry_;
            id_ = other.id_;
            other.registry_ = nullptr;
            other.id_ = kInvalidTaskId;
        }
        return *this;
    }

    AwaitableRef(const AwaitableRef&) = delete;
    AwaitableRef& operator=(const AwaitableRef&) = delete;

    bool is_valid() const noexcept
    {
        return (nullptr != registry_) && static_cast<bool>(id_);
    }

    TaskId id() const noexcept { return id_; }

    bool is_ready() const noexcept
    {
        return is_valid() && registry_->is_ready(id_);
    }

    bool has_error() const noexcept
    {
        return is_valid() && registry_->has_error(id_);
    }

    // Move the result out of the completed slot (one-shot).
    Expected<T, TaskError> take_result() noexcept
    {
        if (!is_valid()) {
            return Expected<T, TaskError>::error(TaskError::kInvalidId);
        }
        return registry_->take_result(id_);
    }

    // Stored error of a completed task, or kOk when none.
    TaskError take_error() const noexcept
    {
        if (!is_valid()) {
            return TaskError::kInvalidId;
        }
        return registry_->take_error(id_);
    }

    // Register the waiter AO (TargetId + resume signal) in the task slot.
    // The completion event is generated by the registry - no callback
    // pointer is ever stored. Rejected when a waiter already exists.
    Expected<void, TaskError> set_awaiter(TargetId waiter,
                                          uint16_t signal) noexcept
    {
        if (!is_valid()) {
            return Expected<void, TaskError>::error(TaskError::kInvalidId);
        }
        return registry_->set_awaiter(id_, waiter, signal);
    }

    // Release the registry slot. The handle becomes invalid.
    Expected<void, TaskError> release() noexcept
    {
        if (!is_valid()) {
            return Expected<void, TaskError>::error(TaskError::kInvalidId);
        }
        const Expected<void, TaskError> result = registry_->release_task(id_);
        registry_ = nullptr;
        id_ = kInvalidTaskId;
        return result;
    }

private:
    RegistryT* registry_;
    TaskId id_;
};

}  // namespace coro
}  // namespace coact
